/**
 * Copies the canonical single-file app into the XrmToolBox plugin output folder.
 *
 * SINGLE SOURCE OF TRUTH:  ../webresource/prx3_UserSecurityRoleTableAccess.html
 *
 * There is deliberately NO skinning step. The HTML detects its host at runtime
 * (window.XTB_CONFIG -> XrmToolBox, window.dataverseAPI -> Power Platform ToolBox,
 * Xrm/same-origin -> D365 web resource) and sets body[data-host], and the stylesheet
 * carries both palettes as Fluent 2 design tokens:
 *
 *   :root                    light  (D365 web resource / standalone - Fluent 2)
 *   body[data-host="pptb"]   dark   (Power Platform ToolBox - dark by default)
 *   body[data-host="xtb"]    light  (XrmToolBox - Fluent 2 light, same as the web resource)
 *
 * That keeps one stylesheet instead of several that drift apart.
 *
 * Output: UserSecurityRoleTableAccess/app/user-access-explorer.html  (bundled into the plugin by the .csproj)
 *
 * The filename must stay UNIQUE. Every XrmToolBox plugin dll lands flat in Plugins, so every
 * WebView2 tool maps its virtual host onto the SAME Plugins/app folder - a generic index.html
 * there is overwritten by whichever tool installs last.
 * Run:    node build-app.js
 */
const fs = require("fs");
const path = require("path");

const root = __dirname;
const src = path.join(root, "..", "webresource", "prx3_UserSecurityRoleTableAccess.html");
const outDir = path.join(root, "UserSecurityRoleTableAccess", "app");
const out = path.join(outDir, "user-access-explorer.html");

if (!fs.existsSync(src)) throw new Error("Canonical HTML not found: " + src);

let html = fs.readFileSync(src, "utf8");
html = html.replace(
  "<title>",
  "<!-- XrmToolBox build - generated by xrmtoolbox/build-app.js from webresource/prx3_UserSecurityRoleTableAccess.html -->\n<title>"
);

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(out, html, "utf8");
console.log("XrmToolBox app written ->", path.relative(root, out), "(" + html.length + " bytes)");
